module "infra-github" {
  source                                                       = "../../modules/infra-github"
  billing_email                                                = var.billing_email
  github_organization                                          = var.github_organization
  github_token                                                 = var.github_token
  github_repositories                                          = var.github_repositories
  company                                                      = var.company
  name                                                         = var.organization_name
  description                                                  = var.organization_description
  default_repository_permission                                = var.default_repository_permission
  members_can_create_public_repositories                       = var.members_can_create_public_repositories
  members_can_create_private_repositories                      = var.members_can_create_private_repositories
  dependabot_alerts_enabled_for_new_repositories               = var.dependabot_alerts_enabled_for_new_repositories
  secret_scanning_enabled_for_new_repositories                 = var.secret_scanning_enabled_for_new_repositories
  advanced_security_enabled_for_new_repositories               = var.advanced_security_enabled_for_new_repositories
  blog                                                         = var.blog
  dependabot_security_updates_enabled_for_new_repositories     = var.dependabot_security_updates_enabled_for_new_repositories
  dependency_graph_enabled_for_new_repositories                = var.dependency_graph_enabled_for_new_repositories
  email                                                        = var.email
  location                                                     = var.location
  members_can_create_internal_repositories                     = var.members_can_create_internal_repositories
  members_can_create_pages                                     = var.members_can_create_pages
  members_can_create_private_pages                             = var.members_can_create_private_pages
  members_can_create_public_pages                              = var.members_can_create_public_pages
  members_can_create_repositories                              = var.members_can_create_repositories
  members_can_fork_private_repositories                        = var.members_can_fork_private_repositories
  secret_scanning_push_protection_enabled_for_new_repositories = var.secret_scanning_push_protection_enabled_for_new_repositories
  twitter_username                                             = var.twitter_username
  web_commit_signoff_required                                  = var.web_commit_signoff_required
  github_organization_variables                                = var.github_organization_variables
  github_teams                                                 = var.github_teams
  webhook_secret_rotation_days                                 = var.webhook_secret_rotation_days

}
